### ISSUE TITLE
fh indices for various plots are wrong on demo script

### ISSUE THREAD

**Issue by soichih** [brain-life/encode#77]
The life demo script shows how to output various plots from probabilistic / deterministic / combined steps. However, the fh indices for probabilistic and deterministic steps uses the same indices so the deterministic steps are overriding the graphs for probabilistic steps.

<probabilistic>
fh(1)
fh(2)
fh(3)
<deterministic>
fh(1) > should be fh(4)
fh(2) > should be fh(5)
fh(3) > should be fh(6)

..and..

<combined>
fh(4) > should be fh(7)
fh(5) > should be fh(8)
fh(6) > should be fh(9)

**Comment by francopestilli** [comment]
@soichih @ccaiafa is this still an issue?

**Comment by ccaiafa** [comment]
fixed. Thanks soichi
