### ISSUE TITLE
feConnectomeInit help text orders the arguments incorrectly

### ISSUE THREAD

**Issue by bcmcpher** [brain-life/encode#83]
feConnectomeInit help text orders the arguments incorrectly. The function appears to work fine otherwise; the arguments are the same, the example in the help has them in the wrong order.

**Comment by francopestilli** [comment]
@bcmcpher @ccaiafa is this still an issue, close?

**Comment by ccaiafa** [comment]
I just checked this. The arguments in the help and in the function are the same and in the same order. Maybe we already fixed this before.
