### ISSUE TITLE
feConnectomeEncoding.m not compatible with Matlab 2014b

### ISSUE THREAD

**Issue by kathrynalpert** [brain-life/encode#87]
When running feConnectomeEncoding.m in Matlab2014b, the `set(s.matlab.desktop.workspace, 'ArraySizeLimitEnabled',false);` line (26) throws an error: "Settings group 'workspace' does not contain setting 'ArraySizeLimitEnabled'." The command works fine with 2015a-2016b, and then it's obviously not run for later versions. 

If there's no such setting in 2014b and/or you don't care to support this version, a note in the README or an error message indicating an unsupported version would be great! Thanks!

**Comment by francopestilli** [comment]
@kathrynalpert thanks. It looks like indeed for that version of matlab the command must be run manually. Is it possibel to run a more recent version fo MatLab on NUNDA?

**Comment by kathrynalpert** [comment]
Certainly. I do think a note in the README or an error message indicating an unsupported version would be great for future users.
